"""add_vertical_niche_to_categories

Revision ID: 5ac6925c87bc
Revises: 5f9f6979154d
Create Date: 2026-06-29 07:18:44.046416

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5ac6925c87bc'
down_revision: Union[str, None] = '5f9f6979154d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_agent_assignment', 'agent_assignments', ['project_id', 'agent_id'])
    op.create_unique_constraint('uq_project_provider', 'ai_provider_configs', ['project_id', 'provider'])
    op.create_foreign_key(None, 'articles', 'articles', ['original_article_id'], ['id'])
    op.create_foreign_key(None, 'articles', 'articles', ['revision_of_article_id'], ['id'])
    op.add_column('categories', sa.Column('vertical', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('niche', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_categories_niche'), 'categories', ['niche'], unique=False)
    op.create_index(op.f('ix_categories_vertical'), 'categories', ['vertical'], unique=False)
    op.add_column('notifications', sa.Column('link', sa.String(length=1000), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('notifications', 'link')
    op.drop_index(op.f('ix_categories_vertical'), table_name='categories')
    op.drop_index(op.f('ix_categories_niche'), table_name='categories')
    op.drop_column('categories', 'niche')
    op.drop_column('categories', 'vertical')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint('uq_project_provider', 'ai_provider_configs', type_='unique')
    op.drop_constraint('uq_project_agent_assignment', 'agent_assignments', type_='unique')
    # ### end Alembic commands ###
