from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum


class AgentCategory(str, Enum):
    research = "research"
    strategy = "strategy"
    creation = "creation"
    review = "review"


class AgentStatus(str, Enum):
    active = "active"
    heuristic = "heuristic"
    partial = "partial"
    planned = "planned"
    disabled = "disabled"


@dataclass
class AgentDef:
    agent_id: str
    name: str
    description: str
    category: AgentCategory
    phase: str = "unknown"
    requires_llm: bool = True
    requires_search: bool = False
    requires_external_api: bool = False
    icon: str = "robot"
    implementation_ref: str | None = None
    status: AgentStatus = AgentStatus.planned
    output_json_field: str | None = None
    visible_in_frontend: bool = True


AGENTS: list[AgentDef] = [
    # ═══════════════════════════════════════════════════════════════════════
    # Phase 1 — Discovery & Topic Selection
    # ═══════════════════════════════════════════════════════════════════════
    AgentDef(
        agent_id="category_context_builder",
        name="Contexte de catégorie",
        description="Prépare le cadre de recherche à partir de la catégorie",
        category=AgentCategory.strategy,
        phase="discovery",
        icon="folder",
        implementation_ref="project_context_service",
        status=AgentStatus.heuristic,
        output_json_field="project_context_json",
    ),
    AgentDef(
        agent_id="demand_discovery",
        name="Découverte de la demande",
        description="Trouve les vraies demandes des internautes",
        category=AgentCategory.research,
        phase="discovery",
        requires_search=True,
        icon="search",
        implementation_ref="idea_discovery_service",
        status=AgentStatus.heuristic,
        output_json_field="idea_discovery_json",
    ),
    AgentDef(
        agent_id="topic_selector",
        name="Sélection de sujet",
        description="Transforme les demandes en sujets éditoriaux",
        category=AgentCategory.strategy,
        phase="discovery",
        icon="target",
        implementation_ref="category_strategy_service",
        status=AgentStatus.heuristic,
        output_json_field="category_strategy_json",
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Phase 2 — SEO Research & Analysis
    # ═══════════════════════════════════════════════════════════════════════
    AgentDef(
        agent_id="keyword_research",
        name="Recherche de mots-clés",
        description="Analyse et suggère des mots-clés SEO pertinents",
        category=AgentCategory.research,
        phase="research",
        requires_search=True,
        icon="search",
        implementation_ref="keyword_brief_service",
        status=AgentStatus.active,
        output_json_field="keyword_brief_json",
    ),
    AgentDef(
        agent_id="search_serp",
        name="Analyse SERP",
        description="Observe les résultats de recherche pour le mot-clé",
        category=AgentCategory.research,
        phase="research",
        requires_search=True,
        requires_external_api=True,
        icon="chart-bar",
        implementation_ref="serp_adapter",
        status=AgentStatus.partial,
        output_json_field="serp_analysis_json",
    ),
    AgentDef(
        agent_id="scraper_extractor",
        name="Extraction de contenu",
        description="Lit les pages sélectionnées pour extraire la structure",
        category=AgentCategory.research,
        phase="research",
        requires_external_api=True,
        icon="file-text",
        implementation_ref="content_extraction_adapter",
        status=AgentStatus.partial,
        output_json_field="extracted_sources_json",
    ),
    AgentDef(
        agent_id="content_gap_analyzer",
        name="Analyse d'écart contenu",
        description="Compare les concurrents et identifie les opportunités",
        category=AgentCategory.research,
        phase="research",
        icon="layers",
        implementation_ref="research_brief_service",
        status=AgentStatus.heuristic,
        output_json_field="content_gap_json",
    ),
    AgentDef(
        agent_id="research_brief",
        name="Brief de recherche",
        description="Transforme les données brutes en synthèse utile",
        category=AgentCategory.research,
        phase="research",
        icon="clipboard",
        implementation_ref="research_brief_service",
        status=AgentStatus.active,
        output_json_field="research_brief_json",
    ),
    AgentDef(
        agent_id="source_quality_checker",
        name="Qualité des sources",
        description="Évalue la fiabilité et la pertinence des sources",
        category=AgentCategory.research,
        phase="research",
        icon="shield",
        status=AgentStatus.heuristic,
        output_json_field="source_quality_report_json",
    ),
    AgentDef(
        agent_id="evidence_pack_builder",
        name="Dossier de preuves",
        description="Crée le dossier de faits et sources validés pour le writer",
        category=AgentCategory.research,
        phase="research",
        icon="briefcase",
        status=AgentStatus.heuristic,
        output_json_field="evidence_pack_json",
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Phase 3 — Strategic Understanding
    # ═══════════════════════════════════════════════════════════════════════
    AgentDef(
        agent_id="intent_analysis",
        name="Analyse d'intention",
        description="Comprend l'intention réelle du lecteur",
        category=AgentCategory.strategy,
        phase="strategy",
        icon="target",
        implementation_ref="intent_analysis_service",
        status=AgentStatus.active,
        output_json_field="intent_analysis_json",
    ),
    AgentDef(
        agent_id="cannibalization_check_initial",
        name="Vérification cannibalisation initiale",
        description="Vérifie si le sujet existe déjà",
        category=AgentCategory.strategy,
        phase="strategy",
        icon="alert-triangle",
        implementation_ref="cannibalization_service",
        status=AgentStatus.active,
        output_json_field="cannibalization_check_json",
    ),
    AgentDef(
        agent_id="editorial_angle",
        name="Angle éditorial",
        description="Choisit comment traiter le sujet",
        category=AgentCategory.strategy,
        phase="strategy",
        icon="edit",
        implementation_ref="editorial_angle_service",
        status=AgentStatus.active,
        output_json_field="editorial_angle_json",
    ),
    AgentDef(
        agent_id="outline_planner",
        name="Plan de l'article",
        description="Construit le plan détaillé de l'article",
        category=AgentCategory.strategy,
        phase="strategy",
        icon="file-text",
        implementation_ref="article_outline_planner",
        status=AgentStatus.active,
        output_json_field="outline_json",
    ),
    AgentDef(
        agent_id="cannibalization_check_outline",
        name="Vérification cannibalisation plan",
        description="Deuxième contrôle de cannibalisation après le plan",
        category=AgentCategory.strategy,
        phase="strategy",
        icon="alert-triangle",
        implementation_ref="cannibalization_service",
        status=AgentStatus.heuristic,
        output_json_field="cannibalization_outline_json",
    ),
    AgentDef(
        agent_id="production_brief_builder",
        name="Brief de production",
        description="Verrouille le brief final pour le writer",
        category=AgentCategory.strategy,
        phase="strategy",
        icon="clipboard",
        implementation_ref="project_context_service",
        status=AgentStatus.active,
        output_json_field="production_brief_json",
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Phase 4 — Cost Estimation
    # ═══════════════════════════════════════════════════════════════════════
    AgentDef(
        agent_id="cost_estimator",
        name="Estimation des coûts",
        description="Estime le coût de génération avant lancement",
        category=AgentCategory.strategy,
        phase="cost",
        requires_llm=False,
        icon="dollar-sign",
        implementation_ref="cost_estimator",
        status=AgentStatus.active,
        output_json_field="estimated_cost_json",
    ),
    AgentDef(
        agent_id="cost_tracker",
        name="Suivi des coûts",
        description="Enregistre les coûts réels pendant l'exécution",
        category=AgentCategory.strategy,
        phase="cost",
        requires_llm=False,
        icon="trending-up",
        status=AgentStatus.active,
        output_json_field=None,
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Phase 5 — Writing & Enrichment
    # ═══════════════════════════════════════════════════════════════════════
    AgentDef(
        agent_id="style_guide_builder",
        name="Guide de style",
        description="Prépare les consignes de style pour la rédaction",
        category=AgentCategory.creation,
        phase="writing",
        icon="book",
        status=AgentStatus.heuristic,
        output_json_field="style_guide_json",
    ),
    AgentDef(
        agent_id="writer",
        name="Rédacteur",
        description="Rédige le contenu principal de l'article",
        category=AgentCategory.creation,
        phase="writing",
        requires_llm=True,
        icon="pen-tool",
        implementation_ref="writing_engine",
        status=AgentStatus.active,
        output_json_field="content_html",
    ),
    AgentDef(
        agent_id="meta_writer",
        name="Rédaction métas",
        description="Prépare les métas (title, description, slug, excerpt)",
        category=AgentCategory.creation,
        phase="writing",
        icon="type",
        implementation_ref="writing_engine",
        status=AgentStatus.active,
        output_json_field=None,
    ),
    AgentDef(
        agent_id="faq_generator",
        name="Génération FAQ",
        description="Crée une FAQ courte et utile (3-6 questions)",
        category=AgentCategory.creation,
        phase="writing",
        icon="help-circle",
        implementation_ref="faq_plan_service",
        status=AgentStatus.active,
        output_json_field="faq_json",
    ),
    AgentDef(
        agent_id="structured_data_builder",
        name="Données structurées",
        description="Génère les données structurées schema.org",
        category=AgentCategory.creation,
        phase="writing",
        requires_llm=False,
        icon="code",
        implementation_ref="structured_data_builder",
        status=AgentStatus.active,
        output_json_field="structured_data_json",
    ),
    AgentDef(
        agent_id="media_planner",
        name="Planification médias",
        description="Propose les images et médias utiles",
        category=AgentCategory.creation,
        phase="writing",
        requires_external_api=True,
        icon="image",
        implementation_ref="image_sourcing_adapter",
        status=AgentStatus.partial,
        output_json_field="image_plan_json",
    ),
    AgentDef(
        agent_id="callout_planner",
        name="Planification callouts",
        description="Propose les encadrés callout pertinents",
        category=AgentCategory.creation,
        phase="writing",
        icon="quote",
        implementation_ref="callout_plan_service",
        status=AgentStatus.active,
        output_json_field="callout_plan_json",
    ),
    AgentDef(
        agent_id="internal_link_planner",
        name="Liens internes",
        description="Propose les liens internes pertinents",
        category=AgentCategory.creation,
        phase="writing",
        icon="link",
        implementation_ref="internal_link_service",
        status=AgentStatus.active,
        output_json_field="internal_links_json",
    ),
    AgentDef(
        agent_id="external_link_planner",
        name="Liens externes",
        description="Propose les liens externes vers des sources fiables",
        category=AgentCategory.creation,
        phase="writing",
        requires_search=True,
        icon="external-link",
        implementation_ref="external_link_service",
        status=AgentStatus.active,
        output_json_field="external_links_json",
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Phase 6 — SEO/GEO Optimization
    # ═══════════════════════════════════════════════════════════════════════
    AgentDef(
        agent_id="seo_optimizer",
        name="Optimisation SEO",
        description="Contrôle et optimise le SEO avancé de l'article",
        category=AgentCategory.review,
        phase="seo",
        icon="search",
        implementation_ref="seo_review_service",
        status=AgentStatus.active,
        output_json_field="seo_review_json",
    ),
    AgentDef(
        agent_id="geo_answer_optimizer",
        name="Optimisation GEO",
        description="Vérifie que l'article est optimisé pour les moteurs IA et réponses génératives",
        category=AgentCategory.review,
        phase="seo",
        requires_llm=False,
        icon="globe",
        implementation_ref="geo_optimizer",
        status=AgentStatus.active,
        output_json_field="geo_optimization_json",
    ),
    AgentDef(
        agent_id="engagement_editor",
        name="Éditeur d'engagement",
        description="Améliore l'engagement et la rétention du lecteur",
        category=AgentCategory.review,
        phase="seo",
        icon="heart",
        status=AgentStatus.planned,
        output_json_field="engagement_report_json",
    ),
    AgentDef(
        agent_id="reader_retention_checker",
        name="Rétention lecteur",
        description="Détecte les points de décrochage du lecteur",
        category=AgentCategory.review,
        phase="seo",
        icon="users",
        status=AgentStatus.planned,
        output_json_field="reader_retention_report_json",
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Phase 7 — Quality Control
    # ═══════════════════════════════════════════════════════════════════════
    AgentDef(
        agent_id="editor",
        name="Révision éditoriale",
        description="Révise le contenu pour la qualité éditoriale globale",
        category=AgentCategory.review,
        phase="quality",
        icon="edit",
        implementation_ref="editorial_quality_gate",
        status=AgentStatus.active,
        output_json_field="editorial_quality_report_json",
    ),
    AgentDef(
        agent_id="language_quality",
        name="Qualité linguistique",
        description="Analyse la qualité de la langue (grammaire, style, orthographe)",
        category=AgentCategory.review,
        phase="quality",
        icon="book",
        implementation_ref="language_quality_service",
        status=AgentStatus.active,
        output_json_field="language_quality_report_json",
    ),
    AgentDef(
        agent_id="originality_checker",
        name="Originalité",
        description="Vérifie l'originalité et détecte le plagiat potentiel",
        category=AgentCategory.review,
        phase="quality",
        icon="copy",
        implementation_ref="originality_service",
        status=AgentStatus.active,
        output_json_field="originality_report_json",
    ),
    AgentDef(
        agent_id="claim_extractor",
        name="Extraction d'affirmations",
        description="Extrait les affirmations vérifiables du contenu",
        category=AgentCategory.research,
        phase="quality",
        icon="check-square",
        status=AgentStatus.heuristic,
        output_json_field="claims_json",
    ),
    AgentDef(
        agent_id="fact_checker",
        name="Vérification des faits",
        description="Vérifie l'exactitude des affirmations et données",
        category=AgentCategory.research,
        phase="quality",
        requires_search=True,
        icon="check-circle",
        implementation_ref="agent_services",
        status=AgentStatus.partial,
        output_json_field="fact_check_report_json",
    ),
    AgentDef(
        agent_id="humanizer",
        name="Humanisation",
        description="Vérifie et améliore le ton naturel du contenu",
        category=AgentCategory.review,
        phase="quality",
        icon="smile",
        implementation_ref="humanization_service",
        status=AgentStatus.active,
        output_json_field="humanization_report_json",
    ),
    AgentDef(
        agent_id="eeat_reviewer",
        name="Review EEAT",
        description="Vérifie la conformité aux critères EEAT de Google",
        category=AgentCategory.review,
        phase="quality",
        icon="shield",
        implementation_ref="eeat_service",
        status=AgentStatus.active,
        output_json_field="eeat_checklist_json",
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Phase 8 — Final Checks
    # ═══════════════════════════════════════════════════════════════════════
    AgentDef(
        agent_id="seo_final_checklist",
        name="Checklist SEO finale",
        description="Vérifie que tous les éléments SEO sont en place avant publication",
        category=AgentCategory.review,
        phase="final",
        requires_llm=False,
        icon="check-list",
        implementation_ref="seo_final_checklist_service",
        status=AgentStatus.active,
        output_json_field="seo_final_checklist_json",
    ),
    AgentDef(
        agent_id="quality_gate",
        name="Porte qualité",
        description="Décide si l'article peut passer en production",
        category=AgentCategory.review,
        phase="final",
        requires_llm=False,
        icon="gate",
        implementation_ref="editorial_quality_gate",
        status=AgentStatus.active,
        output_json_field="editorial_quality_report_json",
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Phase 9 — Reporting
    # ═══════════════════════════════════════════════════════════════════════
    AgentDef(
        agent_id="error_manager",
        name="Gestion des erreurs",
        description="Centralise les erreurs et gère les retries",
        category=AgentCategory.strategy,
        phase="final",
        requires_llm=False,
        icon="alert-circle",
        status=AgentStatus.heuristic,
        output_json_field=None,
    ),
    AgentDef(
        agent_id="generation_report_builder",
        name="Rapport de génération",
        description="Produit le rapport complet de la génération",
        category=AgentCategory.review,
        phase="final",
        requires_llm=False,
        icon="file",
        implementation_ref="generation_report_service",
        status=AgentStatus.active,
        output_json_field="generation_report_json",
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Legacy aliases (kept for backward compatibility)
    # ═══════════════════════════════════════════════════════════════════════
    AgentDef(
        agent_id="serp_analyzer",
        name="Analyse SERP (legacy)",
        description="Ancien nom pour search_serp",
        category=AgentCategory.research,
        phase="research",
        requires_search=True,
        icon="chart-bar",
        implementation_ref="serp_adapter",
        status=AgentStatus.partial,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="trend_detector",
        name="Détection de tendances (legacy)",
        description="Observe les tendances émergentes",
        category=AgentCategory.research,
        phase="research",
        requires_search=True,
        icon="trending-up",
        implementation_ref="trends_adapter",
        status=AgentStatus.partial,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="competitor_analyzer",
        name="Analyse concurrents (legacy)",
        description="Analyse le contenu des concurrents",
        category=AgentCategory.research,
        phase="research",
        requires_search=True,
        icon="users",
        implementation_ref="research_brief_service",
        status=AgentStatus.heuristic,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="researcher",
        name="Recherche (legacy)",
        description="Recherche approfondie sur un sujet",
        category=AgentCategory.research,
        phase="research",
        icon="book-open",
        implementation_ref="content_extraction_adapter",
        status=AgentStatus.partial,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="cannibalization_checker",
        name="Cannibalisation (legacy)",
        description="Ancien nom pour cannibalization_check_initial",
        category=AgentCategory.strategy,
        phase="strategy",
        icon="alert-triangle",
        implementation_ref="cannibalization_service",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="idea_generator",
        name="Génération d'idées (legacy)",
        description="Propose des idées d'articles",
        category=AgentCategory.strategy,
        phase="discovery",
        icon="lightbulb",
        implementation_ref="idea_engine",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="editorial_strategist",
        name="Stratégie éditoriale (legacy)",
        description="Définit la stratégie",
        category=AgentCategory.strategy,
        phase="discovery",
        icon="map",
        implementation_ref="category_strategy_service",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="content_planner",
        name="Planification contenu (legacy)",
        description="Planifie le format de l'article",
        category=AgentCategory.strategy,
        phase="strategy",
        icon="file-text",
        implementation_ref="editorial_angle_service",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="brief_writer",
        name="Rédaction de brief (legacy)",
        description="Rédige le brief éditorial",
        category=AgentCategory.strategy,
        phase="strategy",
        icon="clipboard",
        implementation_ref="project_context_service",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="content_writer",
        name="Rédacteur (legacy)",
        description="Ancien nom pour writer",
        category=AgentCategory.creation,
        phase="writing",
        icon="pen-tool",
        implementation_ref="writing_engine",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="title_generator",
        name="Génération de titres (legacy)",
        description="Génère des titres SEO",
        category=AgentCategory.creation,
        phase="writing",
        icon="type",
        implementation_ref="writing_engine",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="meta_description_writer",
        name="Meta descriptions (legacy)",
        description="Rédige les meta descriptions",
        category=AgentCategory.creation,
        phase="writing",
        icon="align-left",
        implementation_ref="writing_engine",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="image_selector",
        name="Sélection d'images (legacy)",
        description="Ancien nom pour media_planner",
        category=AgentCategory.creation,
        phase="writing",
        icon="image",
        implementation_ref="image_sourcing_adapter",
        status=AgentStatus.partial,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="internal_link_builder",
        name="Liens internes (legacy)",
        description="Ancien nom pour internal_link_planner",
        category=AgentCategory.creation,
        phase="writing",
        icon="link",
        implementation_ref="internal_link_service",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="external_link_finder",
        name="Liens externes (legacy)",
        description="Ancien nom pour external_link_planner",
        category=AgentCategory.creation,
        phase="writing",
        requires_search=True,
        icon="external-link",
        implementation_ref="external_link_service",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="readability_analyzer",
        name="Lisibilité (legacy)",
        description="Analyse la lisibilité",
        category=AgentCategory.review,
        phase="quality",
        icon="book",
        implementation_ref="language_quality_service",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="humanization_engine",
        name="Humanisation (legacy)",
        description="Ancien nom pour humanizer",
        category=AgentCategory.review,
        phase="quality",
        icon="smile",
        implementation_ref="humanization_service",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="eeat_checker",
        name="EEAT (legacy)",
        description="Ancien nom pour eeat_reviewer",
        category=AgentCategory.review,
        phase="quality",
        icon="shield",
        implementation_ref="eeat_service",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="quality_rater",
        name="Évaluation qualité (legacy)",
        description="Ancien nom pour quality_gate",
        category=AgentCategory.review,
        phase="final",
        icon="star",
        implementation_ref="editorial_quality_gate",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
    AgentDef(
        agent_id="editor_revisor",
        name="Révision éditoriale (legacy)",
        description="Ancien nom pour editor",
        category=AgentCategory.review,
        phase="quality",
        icon="edit",
        implementation_ref="editorial_quality_gate",
        status=AgentStatus.active,
        visible_in_frontend=False,
    ),
]

AGENTS_BY_ID = {a.agent_id: a for a in AGENTS}
AGENTS_BY_CATEGORY: dict[str, list[AgentDef]] = {}
for a in AGENTS:
    AGENTS_BY_CATEGORY.setdefault(a.category.value, []).append(a)


def get_agent(agent_id: str) -> AgentDef | None:
    return AGENTS_BY_ID.get(agent_id)


def list_agents(category: str | None = None, visible_only: bool = False) -> list[AgentDef]:
    agents = AGENTS
    if category:
        agents = AGENTS_BY_CATEGORY.get(category, [])
    if visible_only:
        agents = [a for a in agents if a.visible_in_frontend]
    return list(agents)


def serialize_agent(a: AgentDef) -> dict:
    return {
        "agent_id": a.agent_id,
        "name": a.name,
        "description": a.description,
        "category": a.category.value,
        "phase": a.phase,
        "requires_llm": a.requires_llm,
        "requires_search": a.requires_search,
        "requires_external_api": a.requires_external_api,
        "icon": a.icon,
        "has_implementation": a.implementation_ref is not None,
        "status": a.status.value,
        "output_json_field": a.output_json_field,
        "visible_in_frontend": a.visible_in_frontend,
    }
